// Code generated by cmd/genstager; DO NOT EDIT.
package stager

import _ "embed"

//go:embed stager_darwin_arm64.bin
var imageDarwinArm64 []byte

const entryOffsetDarwinArm64 = 0xcdc

func loaderTextDarwinArm64() ([]byte, uint64) {
	return imageDarwinArm64, entryOffsetDarwinArm64
}
